[package]
name = "lib-epub"
authors = ["KikkiZ <zhangyozh@foxmail.com>"]
description = "A library for reading epub files"
keywords = ["epub", "ebook"]
license = "MIT"

version = "0.1.0"
edition = "2024"
rust-version = "1.85"

[dependencies]
chrono = "0.4.42"
log = "0.4.29"
quick-xml = "0.38.4"
sha1 = "0.10.6"
sha2 = "0.10.9"
thiserror = "2.0.17"
zip = { version = "5.1.1", default-features = false, features = ["deflate"] }

[dev-dependencies]
flate2 = "1.1.5"
# kiss_xml = "1.0.2"
